### ISSUE TITLE
Add new entry upon pressing <enter>

### ISSUE THREAD

**Issue by canDry** [davidahmed/wiper#3]
Could you add this to panel.js so that <enter> adds the text:
```

document.getElementById("addURLField")
    .addEventListener("keyup", function(event) {
    event.preventDefault();
    if (event.keyCode === 13) {
        document.getElementById("addURLButton").click();
    }
});

```

**Comment by davidahmed** [comment]
Commit dc270f90edf118f0546652fe52836792d1602cdb resolves the issue. Thanks.

**Comment by davidahmed** [comment]
@canDry I am not familiar with CI on Github (I come from Gitlab) but I would also add a CI hook to the master to build and push the updates to Firefox Add-ons itself. For now expect that I'd be releasing new updates manually (and hence the newer fixes).
