### ISSUE TITLE
Refactor blue border

### ISSUE THREAD

**Issue by Wulfheart** [davidahmed/wiper#7]
When this extension is active in Google there is a small blue border around to indicate that the extension is active. In its current state it is so thin that it is annoying in my opinion.
Please make it thicker or remove it.

**Comment by davidahmed** [comment]
I think i'll make it thicker and with lower luminance (so it's not displeasing to the eyes) and put it on the left side so it doesnt add anything to scrolling range either.

**Comment by davidahmed** [comment]
I am once again picking up where I left. Sorry, but in retrospect I had too much hubris to not consider how annoying it could have been. But now, it's removed in 6b7ddcaa987c042c52a0862952967ad9f86193f4

Also, don't forget to checkout new improvements. If you're using this plugin, then update wiper to see the new things in action.
